### PR TITLE
Add json string escaping

### PR DESCRIPTION
**Pull request by jlewin**
Possible fix for #1, if you're interested.

### CODE REVIEW

**Comment by cvbge** [comment]
Hi @jlewin, could you add some UT?

**Comment by jlewin** [comment]
I'll take a look

**Comment by jlewin** [comment]
I force pushed to my branch, so you may need to drop by prior branch if you pulled it. Otherwise, I've added a few tests and revised the implementation to leave in the leading/trailing quotes, as the other languages do.

Would be interesting to see if you could test for being "inside" of a string block, and remove the leading/trailing quotes in that case, but still quite functional as is.

Let me know if there's anything else that looks off.

**Comment by cvbge** [comment]
Thanks, looks good. I'm merging it.

For detecting "inside string", maybe it could be done. I guess you'd have to parse whole file to be sure, and I guess it still would not be ideal. 

Maybe a simpler solution would be to add a second command that would assume you are pasting inside a string. But then there could be different types of string delimiter, so user could say "paste inside '' string", "paste inside "" string", etc. Now it stops being so simple. But still might be usable.

**Pull request merged**
